//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eam.Ingenieria.Matagym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public System.Guid id { get; set; }
        public string password { get; set; }
        public Nullable<System.Guid> personid { get; set; }
        public string username { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
