//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eam.Ingenieria.Matagym
{
    using System;
    using System.Collections.Generic;
    
    public partial class Measurement
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> Personid { get; set; }
        public double bodyFat { get; set; }
        public System.DateTime date { get; set; }
        public double heartRate { get; set; }
        public double height { get; set; }
        public double weight { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
