//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eam.Ingenieria.Matagym
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__EFMigrationsHistory> C__EFMigrationsHistory { get; set; }
        public virtual DbSet<Challenge> Challenges { get; set; }
        public virtual DbSet<ChallengeStage> ChallengeStages { get; set; }
        public virtual DbSet<Gym> Gyms { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Measurement> Measurements { get; set; }
        public virtual DbSet<NewImage> NewImages { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<PersonRoutine> PersonRoutines { get; set; }
        public virtual DbSet<Person> Persons { get; set; }
        public virtual DbSet<Routine> Routines { get; set; }
        public virtual DbSet<RoutineStage> RoutineStages { get; set; }
        public virtual DbSet<StageImage> StageImages { get; set; }
        public virtual DbSet<Stage> Stages { get; set; }
    }
}
