//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Eam.Ingenieria.Matagym
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewImage
    {
        public System.Guid id { get; set; }
        public Nullable<System.Guid> imageid { get; set; }
        public Nullable<System.Guid> noticeid { get; set; }
    
        public virtual Image Image { get; set; }
        public virtual News News { get; set; }
    }
}
